// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX-_zBsSSkUjDiu7uO2elpCXt693_DYdY',
    appId: '1:12197641408:web:a5731421bd2e74313e0125',
    messagingSenderId: '12197641408',
    projectId: 'random-social-app-project',
    authDomain: 'random-social-app-project.firebaseapp.com',
    storageBucket: 'random-social-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8dWlSCGJAiaA_VJ9UA9coRWtuLs33uiY',
    appId: '1:12197641408:android:e2357acf1f4b428f3e0125',
    messagingSenderId: '12197641408',
    projectId: 'random-social-app-project',
    storageBucket: 'random-social-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFromV7EnXNN9YOqUi0gwbhtpYMTHRvJ0',
    appId: '1:12197641408:ios:0d1be1eec735304d3e0125',
    messagingSenderId: '12197641408',
    projectId: 'random-social-app-project',
    storageBucket: 'random-social-app-project.appspot.com',
    iosBundleId: 'com.example.randomSocialApp',
  );
}
